services:
  mysql_db:
    image: mariadb:11.8
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep mariadbd | grep -v grep || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_backend
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}" 
    volumes:
      - .:/app 
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      mysql_db:
        condition: service_healthy 
    command: ["npm", "run", "start:dev"] 
    networks:
      - app_network
  app_seeder:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: nestjs_seeder
    env_file:
      - .env
    depends_on:
      nestjs_app:
        condition: service_started
      mysql_db:
        condition: service_healthy
    networks:
      - app_network
    command: ["/bin/sh", "-c", "sleep 10 && npm run db:seed && echo 'Seeding completado y contenedor de seeder saliendo.'"]

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge