version: '3.8'

services:
  mysql_db:
    image: mariadb:11.8
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MARIADB_USER", "-p$$MARIADB_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  app_seeder:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: nestjs_seeder
    env_file:
      - .env
    depends_on:
        - mysql_db
    networks:
      - app_network
    volumes:
      - .:/app
      - /app/node_modules
    command: ["/bin/sh", "-c", "sleep 15 && npm run db:seed && tail -f /dev/null"]
    stdin_open: true 
    tty: true  

  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
      - /app/node_modules
    environment:
      PORT: 3000
    env_file:
      - .env
    depends_on:
      app_seeder:
        condition: service_completed_successfully 
      mysql_db:
        condition: service_healthy 
    command: ["npm", "run", "start:dev"] 
    networks:
      - app_network

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge